### ISSUE TITLE
[TASK] Deploy only updates source BU folder in GIT, not the target BU folder (actual deploy works though)

### ISSUE THREAD

**Issue by DannyCastroVentura** [Accenture/sfmc-devtools-copado#130]
**Question:** What should we do on master git branch when running deploy?

- [x] Update the source;
- [x] Update the target;
- [x] Update both;

**Comment by JoernBerkefeld** [comment]
question here is: should deploy.js create one additional commit to update the target bu folder after createDeltaPkg ran or not.


right now we only care about the source BU but never update the target bu folders via copado.
when we use mcdev outside of copado, we actually do tell people to update all BU folders. maybe we should do the same here

**Comment by JoernBerkefeld** [comment]
decision:

in deploy step we will update the folder retrieve/target-bu/ - right now we don't and that's causing us to lose information.

**solution**: after successful deploy, run mcdev.retrieve() like shown in commit.js (it takes a list of types and keys and only downloads relevant information)

why not use what we push into deploy folder instead? because there are sometimes differences in the json format between deploy & retrieve
